# Generated by Django 5.2.10 on 2026-02-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='برای مظنونین، عکس شناسایی یا تصویر مرتبط', null=True, upload_to='user_photos/%Y/%m/%d/', verbose_name='عکس پروفایل / تصویر مظنون'),
        ),
    ]
