# Generated by Django 5.2.10 on 2026-02-18 11:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_initial'),
        ('interrogation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interrogation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='suspect',
            options={'ordering': ['-added_at']},
        ),
        migrations.AddField(
            model_name='interrogation',
            name='captain_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interrogation',
            name='chief_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interrogation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='interrogation',
            name='status',
            field=models.CharField(choices=[('PENDING_SCORES', 'در انتظار ثبت امتیازها'), ('SCORES_COMPLETED', 'امتیازها ثبت شده'), ('PENDING_CAPTAIN', 'در انتظار تصمیم کاپیتان'), ('CAPTAIN_DECIDED', 'کاپیتان تصمیم گرفت'), ('PENDING_CHIEF', 'در انتظار تأیید رئیس پلیس'), ('COMPLETED', 'کامل شده'), ('CANCELLED', 'لغو شده')], default='PENDING_SCORES', max_length=30, verbose_name='وضعیت فرآیند بازجویی'),
        ),
        migrations.AddField(
            model_name='interrogation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suspect',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='suspect',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_suspects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='capitan_comment',
            field=models.TextField(blank=True, default='', verbose_name='نظر / توضیحات کاپیتان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='capitan_verdict',
            field=models.CharField(blank=True, choices=[('GUILTY', 'guilty'), ('NOT_GUILTY', 'not guilty')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='chief_approved',
            field=models.CharField(blank=True, choices=[('APPROVED', 'approved'), ('NOT_APPROVED', 'not approved')], max_length=20, null=True, verbose_name='نظر نهایی رئیس پلیس'),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='detective_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='امتیاز احتمال گناهکاری کارآگاه'),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='interrogator_detective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='interrogations_as_detective', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='interrogator_sergeant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='interrogations_as_sergeant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='sergeant_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='امتیاز احتمال گناهکاری گروهبان'),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='suspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogations', to='interrogation.suspect'),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='suspects', to='case.case'),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='detail',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='suspects_as_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='suspect',
            unique_together={('person', 'case')},
        ),
    ]
