# Generated by Django 6.0.2 on 2026-02-20 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interrogation', '0002_alter_interrogation_options_alter_suspect_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['-created_at'], 'verbose_name': 'دادگاه', 'verbose_name_plural': 'دادگاه\u200cها'},
        ),
        migrations.RemoveField(
            model_name='court',
            name='date',
        ),
        migrations.AddField(
            model_name='court',
            name='hearing_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ دادگاه'),
        ),
        migrations.AddField(
            model_name='court',
            name='punishment_description',
            field=models.TextField(blank=True, verbose_name='توضیحات مجازات'),
        ),
        migrations.AddField(
            model_name='court',
            name='punishment_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان مجازات'),
        ),
        migrations.AddField(
            model_name='court',
            name='verdict_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ صدور حکم'),
        ),
        migrations.AlterField(
            model_name='court',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='final_verdict',
            field=models.CharField(blank=True, choices=[('GUILTY', 'guilty'), ('NOT_GUILTY', 'not guilty')], max_length=20, null=True, verbose_name='حکم نهایی'),
        ),
        migrations.AlterField(
            model_name='court',
            name='interrogation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='court', to='interrogation.interrogation'),
        ),
        migrations.AlterField(
            model_name='court',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='court_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
