# Generated by Django 6.0.2 on 2026-02-26 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interrogation', '0003_alter_court_options_remove_court_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='punishment_description',
        ),
        migrations.RemoveField(
            model_name='court',
            name='punishment_title',
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('payment', models.IntegerField()),
                ('prison_time', models.DurationField()),
                ('is_exile', models.BooleanField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='interrogation.court')),
            ],
        ),
    ]
