# Generated by Django 6.0.2 on 2026-02-17 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0002_initial'),
        ('evidences', '0002_initial'),
        ('interrogation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='case.case', verbose_name='پرونده')),
                ('detective', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='detections_as_detective', to=settings.AUTH_USER_MODEL, verbose_name='کارآگاه')),
                ('sergeant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections_as_sergeant', to=settings.AUTH_USER_MODEL, verbose_name='گروهبان')),
                ('detection_board', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='detection.detectionboard', verbose_name='تخته')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lead_type', models.CharField(choices=[('E', 'Evidence'), ('N', 'Detective Note')], max_length=1)),
                ('content', models.TextField()),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.detectionboard')),
                ('evidence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='evidences.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='SuspectsSuggested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_suggested', models.DateTimeField(auto_now_add=True)),
                ('detective_reasons', models.TextField()),
                ('state', models.SmallIntegerField(choices=[(0, 'PENDING'), (1, 'CONFIRMED'), (2, 'REJECTED')], default=0)),
                ('feedback', models.TextField(blank=True)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='detection.detection')),
                ('suspects', models.ManyToManyField(blank=True, to='interrogation.suspect')),
            ],
            options={
                'ordering': ['-time_suggested'],
            },
        ),
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yarns_as_first', to='detection.lead')),
                ('lead2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yarns_as_second', to='detection.lead')),
            ],
        ),
    ]
