# Generated by Django 6.0.2 on 2026-02-20 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_initial'),
        ('detection', '0002_alter_suspectssuggested_suspects'),
        ('evidences', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='detection', to='case.case', verbose_name='پرونده'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='detection_board',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='detection', to='detection.detectionboard', verbose_name='تخته'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='evidences.evidence'),
        ),
    ]
