# Generated by Django 5.0.7 on 2026-02-17 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crime_type', models.CharField(choices=[('TYPE_3', 'سطح ۳ - جرائم خرد'), ('TYPE_2', 'سطح ۲ - جرائم متوسط'), ('TYPE_1', 'سطح ۱ - جرائم سنگین'), ('CRITICAL', 'بحرانی')], default='TYPE_1', max_length=20, verbose_name='نوع جرم')),
                ('case_number', models.CharField(blank=True, max_length=32, unique=True)),
                ('status', models.CharField(default='OPEN', max_length=64)),
            ],
            options={
                'verbose_name': 'پرونده',
                'verbose_name_plural': 'پرونده\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_to_incident', models.CharField(blank=True, max_length=120, verbose_name='رابطه با حادثه (اختیاری)')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تأیید'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20, verbose_name='وضعیت شاکی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'شاکی پرونده',
                'verbose_name_plural': 'شاکیان پرونده',
            },
        ),
        migrations.CreateModel(
            name='ComplainReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, verbose_name='پیام / دلیل بازگشت یا رد')),
                ('is_approval', models.BooleanField(default=False, verbose_name='تأیید نهایی این مرحله؟')),
                ('to_status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس (فقط شاکی)'), ('PENDING_CADET', 'در انتظار بررسی کارآموز'), ('RETURNED_TO_COMPLAINANT', 'بازگشت به شاکی برای اصلاح'), ('PENDING_OFFICER', 'در انتظار تأیید افسر پلیس'), ('APPROVED', 'پرونده تشکیل شد'), ('REJECTED', 'رد نهایی'), ('CANCELLED', 'باطل شده (بیش از حد ویرایش)')], max_length=32)),
            ],
            options={
                'verbose_name': 'بررسی شکایت',
                'verbose_name_plural': 'بررسی\u200cهای شکایت',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='CrimeSceneReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(verbose_name='زمان وقوع جرم')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان گزارش')),
                ('location', models.CharField(max_length=300, verbose_name='محل دقیق یا تقریبی')),
                ('description', models.TextField(verbose_name='شرح صحنه جرم')),
                ('crime_type', models.CharField(choices=[('TYPE_3', 'سطح ۳ - جرائم خرد'), ('TYPE_2', 'سطح ۲ - جرائم متوسط'), ('TYPE_1', 'سطح ۱ - جرائم سنگین'), ('CRITICAL', 'بحرانی')], default='TYPE_1', max_length=20, verbose_name='نوع جرم')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس مأمور'), ('PENDING_SUPERVISOR', 'در انتظار تأیید مافوق'), ('APPROVED', 'تأیید و تشکیل پرونده'), ('REJECTED', 'رد شده')], default='DRAFT', max_length=32, verbose_name='وضعیت گزارش')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'گزارش صحنه جرم',
                'verbose_name_plural': 'گزارش\u200cهای صحنه جرم',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='CrimeSceneWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی شاهد')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('statement_summary', models.TextField(blank=True, verbose_name='خلاصه اظهارات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'شاهد صحنه جرم',
                'verbose_name_plural': 'شاهدان صحنه جرم',
            },
        ),
        migrations.CreateModel(
            name='RegisterComplain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان شکایت')),
                ('description', models.TextField(verbose_name='شرح کامل شکایت')),
                ('incident_datetime', models.DateTimeField(verbose_name='زمان تقریبی وقوع')),
                ('incident_location', models.CharField(blank=True, max_length=300, verbose_name='محل وقوع')),
                ('crime_type', models.CharField(choices=[('TYPE_3', 'سطح ۳ - جرائم خرد'), ('TYPE_2', 'سطح ۲ - جرائم متوسط'), ('TYPE_1', 'سطح ۱ - جرائم سنگین'), ('CRITICAL', 'بحرانی')], default='TYPE_1', max_length=20, verbose_name='نوع جرم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس (فقط شاکی)'), ('PENDING_CADET', 'در انتظار بررسی کارآموز'), ('RETURNED_TO_COMPLAINANT', 'بازگشت به شاکی برای اصلاح'), ('PENDING_OFFICER', 'در انتظار تأیید افسر پلیس'), ('APPROVED', 'پرونده تشکیل شد'), ('REJECTED', 'رد نهایی'), ('CANCELLED', 'باطل شده (بیش از حد ویرایش)')], default='DRAFT', max_length=32, verbose_name='وضعیت شکایت')),
                ('revision_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد دفعات بازگشت به شاکی')),
                ('max_revisions', models.PositiveSmallIntegerField(default=3, editable=False)),
            ],
            options={
                'verbose_name': 'شکایت اولیه',
                'verbose_name_plural': 'شکایات اولیه',
                'ordering': ['-created_at'],
            },
        ),
    ]
