# Generated by Django 5.0.7 on 2026-02-18 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complainant',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complainants', to='case.case'),
        ),
        migrations.AddField(
            model_name='complainant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complainreview',
            name='reviewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crimescenereport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reported_crime_scenes', to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده (مأمور)'),
        ),
        migrations.AddField(
            model_name='crimescenereport',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_crime_scenes', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده'),
        ),
        migrations.AddField(
            model_name='case',
            name='crime_scene_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case', to='case.crimescenereport'),
        ),
        migrations.AddField(
            model_name='crimescenewitness',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='case.crimescenereport'),
        ),
        migrations.AddField(
            model_name='registercomplain',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_complaints', to=settings.AUTH_USER_MODEL, verbose_name='شاکی اصلی'),
        ),
        migrations.AddField(
            model_name='complainreview',
            name='complain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='case.registercomplain'),
        ),
        migrations.AddField(
            model_name='complainant',
            name='complain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complainants', to='case.registercomplain'),
        ),
        migrations.AddField(
            model_name='case',
            name='complain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case', to='case.registercomplain'),
        ),
        migrations.AlterUniqueTogether(
            name='complainant',
            unique_together={('case', 'user'), ('complain', 'user')},
        ),
    ]
