# Generated by Django 5.2.10 on 2026-02-18 11:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0002_initial'),
        ('interrogation', '0002_alter_interrogation_options_alter_suspect_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardTip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان اطلاعات')),
                ('description', models.TextField(verbose_name='جزئیات اطلاعات ارائه شده')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'در انتظار بررسی اولیه افسر'), ('REJECTED', 'رد شده (بی\u200cاعتبار)'), ('SENT_TO_DETECTIVE', 'ارسال به کارآگاه'), ('ACCEPTED', 'تأیید شده توسط کارآگاه'), ('CANCELLED', 'لغو شده')], default='PENDING_REVIEW', max_length=30)),
                ('officer_review_at', models.DateTimeField(blank=True, null=True)),
                ('officer_note', models.TextField(blank=True, verbose_name='یادداشت افسر (در صورت رد)')),
                ('detective_review_at', models.DateTimeField(blank=True, null=True)),
                ('detective_note', models.TextField(blank=True, verbose_name='یادداشت کارآگاه')),
                ('reward_code', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('reward_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ پاداش (ریال)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.case')),
                ('related_suspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interrogation.suspect')),
                ('reviewed_by_detective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_tips', to=settings.AUTH_USER_MODEL, verbose_name='کارآگاه تأییدکننده')),
                ('reviewed_by_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tips', to=settings.AUTH_USER_MODEL, verbose_name='افسر بررسی\u200cکننده')),
                ('tip_submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_tips', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده اطلاعات')),
            ],
            options={
                'verbose_name': 'اطلاعات ارسالی برای پاداش',
                'verbose_name_plural': 'اطلاعات ارسالی برای پاداش',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
