# Generated by Django 6.0.2 on 2026-02-17 22:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sergeant_score', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('detective_score', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('capitan_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('capitan_verdict', models.CharField(choices=[('GUILTY', 'guilty'), ('NOT_GUILTY', 'not guilty')], max_length=20, null=True)),
                ('chief_approved', models.CharField(choices=[('APPROVED', 'approved'), ('NOT_APPROVED', 'not approved')], max_length=20, null=True)),
                ('interrogator_detective', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='interrogation_detective', to=settings.AUTH_USER_MODEL)),
                ('interrogator_sergeant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='interrogation_sergeant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('final_verdict', models.CharField(choices=[('GUILTY', 'guilty'), ('NOT_GUILTY', 'not guilty')], max_length=20, null=True)),
                ('date', models.DateField()),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('interrogation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='interrogation.interrogation')),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('suspect_status', models.CharField(choices=[('CAPTURED', 'captured'), ('WANTED', 'wanted'), ('MOST_WANTED', 'most wanted')], default='WANTED', max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='case.case')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='interrogation',
            name='suspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='interrogation.suspect'),
        ),
    ]
