# Generated by Django 6.0.2 on 2026-02-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardtip',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان اطلاع\u200cرسانی به کاربر'),
        ),
        migrations.AlterField(
            model_name='rewardtip',
            name='officer_note',
            field=models.TextField(blank=True, verbose_name='یادداشت افسر'),
        ),
    ]
