# Generated by Django 5.0.7 on 2026-02-17 13:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('WITNESS', 'استشهاد / اظهارات شاهدان'), ('BIOLOGICAL', 'شواهد زیستی و پزشکی'), ('VEHICLE', 'وسیله نقلیه'), ('ID_DOCUMENT', 'مدارک شناسایی'), ('OTHER', 'سایر شواهد')], max_length=32, verbose_name='دسته شواهد')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان شواهد')),
                ('description', models.TextField(verbose_name='توضیحات / شرح')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='case.case', verbose_name='پرونده مرتبط')),
            ],
            options={
                'verbose_name': 'شاهد / مدرک',
                'verbose_name_plural': 'شواهد و مدارک',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence_media/%Y/%m/%d/', verbose_name='فایل')),
                ('media_type', models.CharField(choices=[('PHOTO', 'تصویر'), ('VIDEO', 'ویدئو'), ('AUDIO', 'صوت'), ('DOCUMENT', 'سند / PDF')], max_length=20, verbose_name='نوع رسانه')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان آپلود')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیح کوتاه فایل')),
            ],
            options={
                'verbose_name': 'فایل شواهد',
                'verbose_name_plural': 'فایل\u200cهای شواهد',
            },
        ),
        migrations.CreateModel(
            name='IdentityDocumentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='عنوان فیلد (مثلاً شماره کارت، تاریخ صدور)')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='BiologicalEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidences.evidence')),
                ('collected_at', models.DateTimeField(verbose_name='زمان جمع\u200cآوری نمونه')),
                ('collection_location', models.CharField(max_length=300, verbose_name='محل دقیق جمع\u200cآوری')),
                ('coroner_result', models.TextField(blank=True, verbose_name='نتیجه بررسی پزشکی قانونی')),
                ('coroner_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید پزشکی قانونی')),
                ('db_match_result', models.TextField(blank=True, verbose_name='نتیجه تطبیق با بانک داده هویتی')),
                ('db_match_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تطبیق بانک داده')),
            ],
            options={
                'verbose_name': 'شاهد زیستی/پزشکی',
                'verbose_name_plural': 'شواهد زیستی و پزشکی',
            },
            bases=('evidences.evidence',),
        ),
        migrations.CreateModel(
            name='IdentityDocumentEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidences.evidence')),
                ('presumed_owner_name', models.CharField(blank=True, max_length=150, verbose_name='نام احتمالی صاحب مدرک')),
            ],
            options={
                'verbose_name': 'مدرک شناسایی',
                'verbose_name_plural': 'مدارک شناسایی پیدا شده',
            },
            bases=('evidences.evidence',),
        ),
        migrations.CreateModel(
            name='OtherEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidences.evidence')),
            ],
            options={
                'verbose_name': 'سایر شواهد',
                'verbose_name_plural': 'سایر شواهد',
            },
            bases=('evidences.evidence',),
        ),
        migrations.CreateModel(
            name='VehicleEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidences.evidence')),
                ('vehicle_model', models.CharField(max_length=100, verbose_name='مدل خودرو')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('license_plate', models.CharField(blank=True, max_length=20, verbose_name='شماره پلاک')),
                ('serial_number', models.CharField(blank=True, max_length=50, verbose_name='شماره شاسی / VIN / سریال')),
            ],
            options={
                'verbose_name': 'مدرک وسیله نقلیه',
                'verbose_name_plural': 'مدارک وسایل نقلیه',
            },
            bases=('evidences.evidence',),
        ),
        migrations.CreateModel(
            name='WitnessStatement',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidences.evidence')),
                ('witness_name', models.CharField(max_length=150, verbose_name='نام شاهد / فرد اظهارکننده')),
                ('witness_national_id', models.CharField(blank=True, max_length=10, verbose_name='کد ملی شاهد (اختیاری)')),
                ('witness_phone', models.CharField(blank=True, max_length=11, verbose_name='شماره تماس شاهد (اختیاری)')),
                ('statement_datetime', models.DateTimeField(blank=True, null=True, verbose_name='زمان اخذ اظهارات')),
            ],
            options={
                'verbose_name': 'استشهاد شاهد',
                'verbose_name_plural': 'استشهادات شاهدان',
            },
            bases=('evidences.evidence',),
        ),
    ]
