# Generated by Django 5.0.7 on 2026-02-16 10:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='case.case')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence_media/%Y/%m/%d')),
                ('media_type', models.CharField(choices=[('PHOTO', 'Photo'), ('VID', 'Video'), ('AUD', 'Audio')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IdDocumentProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BiologicalEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidences.evidence')),
                ('is_accepted', models.BooleanField(default=False)),
            ],
            bases=('evidences.evidence',),
        ),
        migrations.CreateModel(
            name='IdDocumentEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidences.evidence')),
                ('owner_name', models.CharField(max_length=255)),
            ],
            bases=('evidences.evidence',),
        ),
        migrations.CreateModel(
            name='OtherEvidences',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidences.evidence')),
                ('detail', models.CharField(max_length=255)),
            ],
            bases=('evidences.evidence',),
        ),
        migrations.CreateModel(
            name='VehicleEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidences.evidence')),
                ('model', models.CharField(max_length=255)),
                ('license_plate', models.CharField(max_length=13)),
                ('color', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=255)),
            ],
            bases=('evidences.evidence',),
        ),
    ]
