# Generated by Django 5.0.7 on 2026-02-18 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registered_evidences', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='evidencemedia',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='evidences.evidence'),
        ),
        migrations.AddField(
            model_name='evidencemedia',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده'),
        ),
        migrations.AddField(
            model_name='biologicalevidence',
            name='coroner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='verified_biological_evidences', to=settings.AUTH_USER_MODEL, verbose_name='پزشک قانونی تأییدکننده'),
        ),
        migrations.AddField(
            model_name='identitydocumentfield',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='evidences.identitydocumentevidence'),
        ),
        migrations.AlterUniqueTogether(
            name='identitydocumentfield',
            unique_together={('document', 'key')},
        ),
    ]
