# Generated by Django 5.0.7 on 2026-02-16 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0002_initial'),
        ('evidences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencemedia',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='evidences.evidence'),
        ),
        migrations.AddField(
            model_name='witness',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='case.case'),
        ),
        migrations.AddField(
            model_name='witness',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iddocumentproperty',
            name='id_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='evidences.iddocumentevidence'),
        ),
    ]
